# Generated by Django 6.0.4 on 2026-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(help_text='Vous pouvez utiliser du HTML simple (balises <br>, <strong>, etc.)')),
            ],
        ),
    ]
